# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html
resolver: lts-9.21

packages:
- '.'

extra-deps:
  - datetime-0.3.1
  - megaparsec-5.0.1
  - directory-1.2.7.0

flags: {}

extra-package-dbs: []
